### ISSUE TITLE
problem with recalbox 6

### ISSUE THREAD

**Issue by rescoffi45** [Emulga/theme-emulga-box#1]
your theme is amazing but there are some bugs with the latest version of recalbox 6 rc1, for example some images systems disappear, white screen on certain games list, could you update your excellent theme ?
thank you

**Comment by gravelfreeman** [comment]
This is not an issue with the theme. Since the latest Recalbox versions they added more stuff and the VRAM is fully loaded. This theme will not work correctly on Raspberry Pi 3B+ and less. You'll need to use it with Recalbox x86, x64, Odroid XU4, etc.
