### ISSUE TITLE
RetroPie port?

### ISSUE THREAD

**Issue by rollecode** [Emulga/theme-emulga-box#2]
I love this theme! However, I use RetroPie that uses also emulationstation. Doesn't work out of the box. Would it be possible to port it to RetroPie in some way. I could even donate some money for this, because this theme is perfect.

**Comment by gravelfreeman** [comment]
There's currently no plan for me to release this over Retropie. I'm running out of time and I don't use Retropie. I'm not even using Recalbox anymore. If you have a ridiculous amount of money to spend on a Retropie port I could check this out. Thanks for liking my work!
